export { default as Home } from './Home'
export { default as Services } from './Services'
export { default as About } from './About'
export { default as Projects } from './Projects'
export { default as Project } from './Project'
export { default as ContactUs } from './ContactUs'