export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as HomeContainer } from './Home'
export { default as AboutUs } from './About-us'
export { default as ServicesContainer } from './Services'
export { default as ProjectsContainerPage } from './ProjectsContainerPage'
export { default as ContactUsContainerPage } from './ContactUsContainerPage'
export { default as ProjectContainerPage } from './ProjectContainerPage/index'